require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
    - 'bin/**'
    - 'tmp/**/*'
    - 'storage/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Metrics/ClassLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Capybara/FeatureMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
