test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

azure_dev:
  service: AzureStorage
  storage_account_name: <%= ENV['AZURE_STORAGE_ACCOUNT_NAME'] %>
  storage_access_key: <%= ENV['AZURE_STORAGE_KEY'] %>
  container: <%= ENV['AZURE_STORAGE_CONTAINER'] %>

azure_prod:
  service: AzureStorage
  storage_account_name: <%= "babywearing#{Rails.application.config.short_server_name}imgs" %>
  storage_access_key: <%= Rails.application.credentials&.fetch(:azure_storage, nil)&.
                              fetch(Rails.application.config.short_server_name.to_sym, nil) %>
  container: <%= "babywearing#{Rails.application.config.short_server_name}imgs-container" %>
