---
- name: Copy system service file
  become: yes
  copy:
    src: puma.service
    dest: /etc/systemd/system

- name: Enable puma service
  become: yes
  systemd:
    name: puma
    enabled: yes

- name: Force systemd to reread configs
  become: yes
  systemd:
    daemon_reload: yes
